---
# MegaLinter config v9
DISABLE_LINTERS:
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - COPYPASTE
  - JAVASCRIPT_STANDARD
  - REPOSITORY_KINGFISHER
  - REPOSITORY_GIT_DIFF
  - YAML_V8R
  - MARKDOWN_MARKDOWNLINT

SHOW_ELAPSED_TIME: true
