---
ENABLE:
  - JAVA_PMD
  - JAVA_CHECKSTYLE
  - JAVA_SPOTBUGS
  - GO_VET
  - GO_LINT
  - GO_FMT
  - GO_CYCLONE
  - JAVASCRIPT_ES
  - JAVASCRIPT_PRETTIER
  - TYPESCRIPT_ES
  - TYPESCRIPT_PRETTIER
  - PYTHON_PYLINT
  - PYTHON_FLAKE8
  - PYTHON_BLACK
  - YAML_YAMLLINT
  - JSON_JSONLINT
  - MARKDOWN_MARKDOWNLINT
  - SHELL_SHFMT
  - DOCKERFILE_HADOLINT
  - GITHUB_ACTIONS_ACTIONLINT

DISABLE:
  - COPYPASTE
  - SPELL

SHOW_ELAPSED_TIME: true
