MAIN:
  PLUGINS: []
  GITHUB_COMMENT: true
  ENFORCE_JAVA: true
  ENFORCE_GO: true
  ENFORCE_JAVASCRIPT: true
  ENFORCE_TYPESCRIPT: true
  ENFORCE_PYTHON: true
  ENFORCE_YAML: true
  ENFORCE_JSON: true
  ENFORCE_MARKDOWN: true
  ENFORCE_SHELL: true
  ENFORCE_DOCKER: true
  ENFORCE_GITHUB_ACTIONS: true

JAVA:
  JAVA_PMD: true
  JAVA_CHECKSTYLE: true
  JAVA_SPOTBUGS: true

GO:
  GO_VET: true
  GO_LINT: true
  GO_FMT: true
  GO_CYCLONE: true

JAVASCRIPT:
  JAVASCRIPT_ES: true
  JAVASCRIPT_PRETTIER: true

TYPESCRIPT:
  TYPESCRIPT_ES: true
  TYPESCRIPT_PRETTIER: true

PYTHON:
  PYTHON_PYLINT: true
  PYTHON_FLAKE8: true
  PYTHON_BLACK: true

YAML:
  YAML_YAMLLINT: true

JSON:
  JSON_JSONLINT: true

MARKDOWN:
  MARKDOWN_MARKDOWNLINT: true

SHELL:
  SHELL_SHFMT: true

DOCKER:
  DOCKERFILE_HADOLINT: true

GITHUB_ACTIONS:
  GITHUB_ACTIONS_ACTIONLINT: true

DISABLE:
  - COPYPASTE
  - SPELL

SHOW_ELAPSED_TIME: true
